package com.vteam.xml_project.hibernate.example;

// Generated Sep 16, 2012 4:59:46 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserActivation generated by hbm2java
 */
@Entity
@Table(name = "user_activation", catalog = "lucking")
public class UserActivation implements java.io.Serializable {

	private String userUid;
	private User user;
	private String activationCode;

	public UserActivation() {
	}

	public UserActivation(String userUid, User user, String activationCode) {
		this.userUid = userUid;
		this.user = user;
		this.activationCode = activationCode;
	}

	@Id
	@Column(name = "user_uid", unique = true, nullable = false, length = 20)
	public String getUserUid() {
		return this.userUid;
	}

	public void setUserUid(String userUid) {
		this.userUid = userUid;
	}

	@ManyToOne(targetEntity=User.class,fetch = FetchType.LAZY)
	@JoinColumn(name = "user_uid", unique = true, nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "activation_code", nullable = false, length = 40)
	public String getActivationCode() {
		return this.activationCode;
	}

	public void setActivationCode(String activationCode) {
		this.activationCode = activationCode;
	}

}
