package com.vteam.xml_project.hibernate.example;
// Generated Sep 16, 2012 4:59:46 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "lucking")
public class User implements java.io.Serializable {

    private String uuid;
    private UserProfile userProfile;
    private String password;
    private Status status;
    private Set userActivations = new HashSet(0);
    private Set routeses = new HashSet(0);

    public User() {
    }

    public User(String uuid, UserProfile userProfile, String password, Status status) {
        this.uuid = uuid;
        this.userProfile = userProfile;
        this.password = password;
        this.status = status;
    }

    public User(String uuid, UserProfile userProfile, String password, Status status, Set userActivations, Set routeses) {
        this.uuid = uuid;
        this.userProfile = userProfile;
        this.password = password;
        this.status = status;
        this.userActivations = userActivations;
        this.routeses = routeses;
    }

    @Id
    @Column(name = "uuid", unique = true, nullable = false, length = 20)
    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_profile", nullable = false)
    public UserProfile getUserProfile() {
        return this.userProfile;
    }

    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }

    @Column(name = "password", nullable = false, length = 254)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
    public enum Status{
        ACTIVED,UNACTIVED,BANNED
    }

    @Enumerated(EnumType.ORDINAL)
    @Column(name = "status", nullable = false,columnDefinition = "TINYINT")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @OneToMany(targetEntity=UserActivation.class,cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
    public Set getUserActivations() {
        return this.userActivations;
    }

    public void setUserActivations(Set userActivations) {
        this.userActivations = userActivations;
    }

    //@OneToMany(targetEntity=Routes.class,cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "user")
    public Set getRouteses() {
        return this.routeses;
    }

    public void setRouteses(Set routeses) {
        this.routeses = routeses;
    }
}
