package com.vteam.xml_project.hibernate.example;

// Generated Sep 16, 2012 4:59:46 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", catalog = "lucking")
public class UserProfile implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String phoneNumber;
	private Set users = new HashSet(0);

	public UserProfile() {
	}

	public UserProfile(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public UserProfile(String name, String email, String phoneNumber, Set users) {
		this.name = name;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_number", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@OneToMany(targetEntity=User.class,cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "userProfile")
	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
