package com.vteam.xml_project.hibernate.orm;
// Generated Mar 11, 2013 2:33:25 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BidHistory generated by hbm2java
 */
@Entity
@Table(name = "tbl_bid_history", catalog = "xml_project")
public class BidHistory implements java.io.Serializable {

    private Integer id;
    private Users tblUsers;
    private Bids tblBids;
    private double price;
    private Date bidTime;

    public BidHistory() {
    }

    public BidHistory(Users tblUsers, Bids tblBids, double price) {
        this.tblUsers = tblUsers;
        this.tblBids = tblBids;
        this.price = price;
    }

    public BidHistory(Users tblUsers, Bids tblBids, double price, Date bidTime) {
        this.tblUsers = tblUsers;
        this.tblBids = tblBids;
        this.price = price;
        this.bidTime = bidTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public Users getTblUsers() {
        return this.tblUsers;
    }

    public void setTblUsers(Users tblUsers) {
        this.tblUsers = tblUsers;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bid_id", nullable = false)
    public Bids getTblBids() {
        return this.tblBids;
    }

    public void setTblBids(Bids tblBids) {
        this.tblBids = tblBids;
    }

    @Column(name = "price", nullable = false, precision = 22, scale = 0)
    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "bid_time", length = 19)
    public Date getBidTime() {
        return this.bidTime;
    }

    public void setBidTime(Date bidTime) {
        this.bidTime = bidTime;
    }
}
