package com.vteam.xml_project.hibernate.orm;
// Generated Mar 11, 2013 2:33:25 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bids generated by hbm2java
 */
@Entity
@Table(name="tbl_bids"
    ,catalog="xml_project"
)
public class Bids  implements java.io.Serializable {


     private Integer id;
     private Product tblProduct;
     private int lastUserid;
     private double currentPrice;
     private Date startDate;
     private Date endDate;
     private Date lastEdit;
     private Set<BidHistory> tblBidHistories = new HashSet<BidHistory>();

    public Bids() {
    }

	
    public Bids(Product tblProduct, int lastUserid, double currentPrice, Date startDate) {
        this.tblProduct = tblProduct;
        this.lastUserid = lastUserid;
        this.currentPrice = currentPrice;
        this.startDate = startDate;
    }
    public Bids(Product tblProduct, int lastUserid, double currentPrice, Date startDate, Date endDate, Date lastEdit, Set tblBidHistories) {
       this.tblProduct = tblProduct;
       this.lastUserid = lastUserid;
       this.currentPrice = currentPrice;
       this.startDate = startDate;
       this.endDate = endDate;
       this.lastEdit = lastEdit;
       this.tblBidHistories = tblBidHistories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getTblProduct() {
        return this.tblProduct;
    }
    
    public void setTblProduct(Product tblProduct) {
        this.tblProduct = tblProduct;
    }
    
    @Column(name="last_userid", nullable=false)
    public int getLastUserid() {
        return this.lastUserid;
    }
    
    public void setLastUserid(int lastUserid) {
        this.lastUserid = lastUserid;
    }
    
    @Column(name="current_price", nullable=false, precision=22, scale=0)
    public double getCurrentPrice() {
        return this.currentPrice;
    }
    
    public void setCurrentPrice(double currentPrice) {
        this.currentPrice = currentPrice;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", nullable=false, length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_edit", length=19)
    public Date getLastEdit() {
        return this.lastEdit;
    }
    
    public void setLastEdit(Date lastEdit) {
        this.lastEdit = lastEdit;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblBids")
    public Set<BidHistory> getTblBidHistories() {
        return this.tblBidHistories;
    }
    
    public void setTblBidHistories(Set tblBidHistories) {
        this.tblBidHistories = tblBidHistories;
    }




}


