package com.vteam.xml_project.hibernate.orm;
// Generated Mar 11, 2013 2:33:25 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="tbl_category"
    ,catalog="xml_project"
)
public class Category  implements java.io.Serializable {


     private Integer id;
     private String categoryName;
     private String description;
     private Set tblProducts = new HashSet(0);

    public Category() {
    }

	
    public Category(String categoryName, String description) {
        this.categoryName = categoryName;
        this.description = description;
    }
    public Category(String categoryName, String description, Set tblProducts) {
       this.categoryName = categoryName;
       this.description = description;
       this.tblProducts = tblProducts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="category_name", nullable=false, length=50)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    
    @Column(name="description", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblCategory")
    public Set getTblProducts() {
        return this.tblProducts;
    }
    
    public void setTblProducts(Set tblProducts) {
        this.tblProducts = tblProducts;
    }




}


