package com.vteam.xml_project.hibernate.orm;
// Generated Mar 11, 2013 2:33:25 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TagsProduct generated by hbm2java
 */
@Entity
@Table(name="tbl_tags_product"
    ,catalog="xml_project"
)
public class TagsProduct  implements java.io.Serializable {


     private Integer id;
     private Product tblProduct;
     private Tags tblTags;

    public TagsProduct() {
    }

    public TagsProduct(Product tblProduct, Tags tblTags) {
       this.tblProduct = tblProduct;
       this.tblTags = tblTags;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getTblProduct() {
        return this.tblProduct;
    }
    
    public void setTblProduct(Product tblProduct) {
        this.tblProduct = tblProduct;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tags_id", nullable=false)
    public Tags getTblTags() {
        return this.tblTags;
    }
    
    public void setTblTags(Tags tblTags) {
        this.tblTags = tblTags;
    }




}


