package com.vteam.xml_project.hibernate.orm;
// Generated Mar 11, 2013 2:33:25 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserPayment generated by hbm2java
 */
@Entity
@Table(name="tbl_user_payment"
    ,catalog="xml_project"
)
public class UserPayment  implements java.io.Serializable {


     private Integer id;
     private Users tblUsers;
     private Date paymentDay;
     private String cardCode;
     private int amount;

    public UserPayment() {
    }

    public UserPayment(Users user, Date paymentDay, String cardCode, int amount) {
       this.tblUsers = user;
       this.paymentDay = paymentDay;
       this.cardCode = cardCode;
       this.amount = amount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.tblUsers;
    }
    
    public void setUsers(Users user) {
        this.tblUsers = user;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="payment_day", nullable=false, length=19)
    public Date getPaymentDay() {
        return this.paymentDay;
    }
    
    public void setPaymentDay(Date paymentDay) {
        this.paymentDay = paymentDay;
    }
    
    @Column(name="card_code", nullable=false, length=20)
    public String getCardCode() {
        return this.cardCode;
    }
    
    public void setCardCode(String cardCode) {
        this.cardCode = cardCode;
    }
    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }




}


